# Generated by Django 4.2.18 on 2025-02-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="trade_time",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
