# Generated by Django 4.2.18 on 2025-02-10 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0003_remove_trade_trade_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="trade", name="trade_type",),
        migrations.AddField(
            model_name="trade",
            name="trade_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
