# Generated by Django 4.2.18 on 2025-02-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_google_id_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(model_name="botstatistics", name="bot",),
        migrations.RemoveField(model_name="trade", name="bot",),
        migrations.RemoveField(model_name="trade", name="user",),
        migrations.DeleteModel(name="Bot",),
        migrations.DeleteModel(name="BotStatistics",),
        migrations.DeleteModel(name="Trade",),
    ]
